In [11]:

import pandas as pd
rbvr = pd.read_csv("/Users/xavier/Desktop/DSPP/DS/Data-Science-1-Final-Project/Submission_Content/Fig_Data/Rev_Bin_Var_Reliance.csv")
rbvr = rbvr.iloc[: , 1:]
rbvr

         variable        vi       std           low      high
0       bank_prev  0.941025  0.007683  9.256581e-01  0.956392
1        internet  0.034242  0.001899  3.044361e-02  0.038040
2         poverty  0.030343  0.001974  2.639587e-02  0.034290
3   White_or_AAPI  0.028980  0.001734  2.551198e-02  0.032449
4     native_born  0.008438  0.000599  7.239270e-03  0.009636
5         inc_vol  0.006087  0.001319  3.449423e-03  0.008725
6        children  0.004847  0.000991  2.865787e-03  0.006828
7         citizen  0.001574  0.000219  1.136452e-03  0.002011
8   single_mother  0.000297  0.000112  7.256962e-05  0.000521
9        under_25  0.000016  0.000008 -4.025895e-07  0.000032
10     unemployed  0.000000  0.000000  0.000000e+00  0.000000

In [12]:
import sphinx-togglebutton

SyntaxError: invalid syntax (<ipython-input-12-006344cfbb03>, line 1)